export PYTHONWARNINGS="ignore::UserWarning"
cd ..
# 执行小时级任务
python -u run.py \
  --is_training 1 \
  --root_path ./dataset/ \
  --dataset_class 'ylydyg_MD' \
  --draw_num 43 \
  --model AnaNET \
  --features 'S' \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --size 24 \
  --major 96 \
  --e_layers 1 \
  --d_layers 1 \
  --enc_in 1 \
  --dec_in 1 \
  --c_out 1 \
  --d_model 256 \
  --itr 1 \
  --dropout 0.05 \
  --patience 3 \
  --d_ff 1024 \
  --train_epochs 10 \
  --freq 't'

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/ \
  --dataset_class 'bchyxcl_MD' \
  --draw_num 11 \
  --model AnaNET \
  --features 'S' \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --size 24 \
  --major 96 \
  --e_layers 1 \
  --d_layers 1 \
  --enc_in 1 \
  --dec_in 1 \
  --c_out 1 \
  --d_model 256 \
  --itr 1 \
  --dropout 0.05 \
  --patience 3 \
  --d_ff 1024 \
  --train_epochs 10 \
  --freq 't'

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/ \
  --dataset_class 'jbxsssn_MD' \
  --draw_num 9 \
  --model AnaNET \
  --features 'S' \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --size 24 \
  --major 96 \
  --e_layers 1 \
  --d_layers 1 \
  --enc_in 1 \
  --dec_in 1 \
  --c_out 1 \
  --d_model 256 \
  --itr 1 \
  --dropout 0.05 \
  --patience 3 \
  --d_ff 1024 \
  --train_epochs 10 \
  --freq 't'

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/ \
  --dataset_class 'sxsq_MD' \
  --draw_num 15 \
  --model AnaNET \
  --features 'S' \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --size 24 \
  --major 96 \
  --e_layers 1 \
  --d_layers 1 \
  --enc_in 1 \
  --dec_in 1 \
  --c_out 1 \
  --d_model 256 \
  --itr 1 \
  --dropout 0.05 \
  --training_metric 'mae' \
  --patience 3 \
  --d_ff 1024 \
  --train_epochs 10 \
  --freq 't'

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/ \
  --dataset_class 'sxxy_MD' \
  --draw_num 0 \
  --model AnaNET \
  --features 'S' \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --size 24 \
  --major 96 \
  --e_layers 1 \
  --d_layers 1 \
  --enc_in 1 \
  --dec_in 1 \
  --c_out 1 \
  --d_model 256 \
  --itr 1 \
  --dropout 0.05 \
  --training_metric 'mae' \
  --patience 3 \
  --d_ff 1024 \
  --train_epochs 10 \
  --freq 't'

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/ \
  --dataset_class 'bjkd_MD' \
  --draw_num 42 \
  --model AnaNET \
  --features 'S' \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --size 24 \
  --major 96 \
  --e_layers 1 \
  --d_layers 1 \
  --enc_in 1 \
  --dec_in 1 \
  --c_out 1 \
  --d_model 256 \
  --itr 1 \
  --dropout 0.05 \
  --training_metric 'mae' \
  --patience 3 \
  --d_ff 1024 \
  --train_epochs 10 \
  --freq 't'

